---
title: "STATS 205: Homework Assignment 2 (Spring 2019)"
author: ""
date: "4/12/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Solve these problems from the textbooks [HWC](https://onlinelibrary.wiley.com/doi/book/10.1002/9781119196037), **W**, and **ET**.

Send your Rmd and PDF files to pjeganat [at] stanford [dot] edu.

**Due on 4/19/2019 at 1.30 p.m.**


1) [**HWC**: page 58, problem 20](https://onlinelibrary.wiley.com/doi/book/10.1002/9781119196037) (sensitivity to gross errors- mean and HL)

2) [**HWC**: age 58, problem 25](https://onlinelibrary.wiley.com/doi/book/10.1002/9781119196037) (influence by outlying observations - mean and HL)

3) [**HWC**: age 79, problem 60](https://onlinelibrary.wiley.com/doi/book/10.1002/9781119196037) (sensitivity to gross errors- mean and median)

4) (**W**: page 39, problem 11.) Let $X_{1}, \cdots, X_{n} \sim \text{Uniform}\left(0, \theta \right)$. The estimator of interest is $\hat{\theta} = X_{\text{max}} = \text{max}\lbrace X_{1}, \cdots, X_{n}\rbrace$. Generate a data set of size 50 with $\theta = 1$.
    (i) Find the distribution of $\hat{\theta}$ by generating 100,000 samples of sample size 50 from $\text{Uniform}\left(0, 1\right)$ (this will give an approximation to the true distribution of $\hat{\theta}$).
    (ii) Compare the true distribution of $\hat{\theta}$ in (i) to the histogram from the nonparametric bootstraps. Use QQ-plot to compare the true distribution and bootstrap sampling distribution of $\hat{\theta}$.
    
5) (**W**: page 39, problem 12.) Suppose that 50 people are given placebo and 50 are given a new treatment. Thirty placebo patients show improvement, while 40 treated patients show improvement. Let $\tau = p_{1} - p_{2}$ where $p_{2}$ is the probability of improving under treatment and $p_{1}$ is the probability of improving under placebo.
    (i) Find the maximum likelihood estimate of $\tau$.
    (ii) Find the standard error of the maximum likelihood estimate $\hat{\tau}$ using the bootstrap.
    (iii) Find the 90\% percentile confidence interval for $\tau$ using the bootstrap.
    
6) (**ET**: page 152, problem 11.3.) Generate 100 samples $X_{1}, \cdots, X_{20}$ from a normal population $\text{N}\left(\theta, 1 \right)$ with $\theta = 1$.
    (i) For each sample compute the bootstrap and jackknife estimate of variance for $\hat{\theta} = \bar{X}$ and compute the mean and standard deviation of these variance estimates over the 100 samples. 
    (ii) Repeat (a) for the the statistic $\hat{\theta} = \bar{X}^{2}$, and compare the results. Give an explanation for your findings.
    