---
title: "STATS 205: Homework Assignment 7 (Spring 2019)"
author: ""
date: "5/27/2019"
output:
  pdf_document: 
    includes:
      in_header: header.tex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

Solve problems 1-4 from the textbook **HWC** [available here](https://onlinelibrary.wiley.com/doi/book/10.1002/9781119196037) and problem 5.

Send your Rmd and PDF files to pjeganat [at] stanford [dot] edu.

**Due on 5/31/2019 (Friday) at 1.30 p.m**. \rc __Optional:__ \bc This homework assignment can be used to replace the least score/not submitted homework assignment. 

1) **HWC** Page 212, Problem 1.

Pretherapy training of clients has been shown to have beneficial effects on the process and outcome of counseling and psychotherapy. Sauber (1971) investigated four different approaches to pretherapy training:
1. Control (no treatment).
2. Therapeutic reading (TR) (indirect learning).
3. Vicarious therapy pretraining (VTP) (videotaped, vicarious learning). 4. Group, role induction interview (RII) (direct learning).
Treatment conditions 2–4 were expected to enhance the outcome of counseling and psychotherapy as compared with a control group, those subjects receiving no prior set of structuring procedures. One of the major variables of the study was that of “psychotherapeutic attraction.” The basic data in **Table 6.2** consist of the raw scores for this measure according to each of the four experimental conditions. Apply procedure large-sample approximation of Kruskal-Wallis test. What is the null and alternative hypothesis? What are your conclusions?

2) **HWC** Page 265, Problem 47.

Apply the multiple comparison procedure to the psychotherapeutic attraction data of Table 6.2.

3) **HWC** Page 301, Problem 1.

Goldsmith and Nadel (1969) have studied respiratory function following exposure to various levels of ozone for periods of 1 h. The subjects were four presumably healthy males employed by the California State Department of Public Health. The objective measurement used was airway resistance as evaluated by the body plethysmographic technique (see DuBois et al. (1956) and Comroe, Botelho, and DuBois (1959)). Goldsmith and Nadel reported average val- ues for four consecutive measurements taken immediately prior to and again about 5 min after termination of each level of ozone exposure. **Table 7.2** is based on a subset of the Goldsmith- Nadel data, where the tabled values are average airway resistance after ozone exposure minus average airway resistance prior to ozone exposure. Use Friedman's test procedure to test $\text{H}_{0}$. What is the null and alternative hypothesis? What are your conclusions?

4) **HWC** Page 321, Problem 31.

Apply multiple comparison procedure to the ozone exposure data of **Table 7.2**.

5) Perform median polish on **Table 7.2**. What are you conclusions? Do model fit evaluations using Tukey additivity plot. What are your conclusions?

